services:
  pg-backup-restore:
    image: ghcr.io/cswni/pg-backup-restore-cli:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backups:/backups
    environment:
      PORT: "3000"
      BASIC_AUTH_USER: ${BASIC_AUTH_USER:-admin}
      BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD:?BASIC_AUTH_PASSWORD must be set}
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-premas
        - traefik.constraint-label=traefik-local
        - traefik.http.routers.pg-backup-restore.rule=Host(`pgui.premas.net`)
        - traefik.http.routers.pg-backup-restore.entrypoints=https
        - traefik.http.routers.pg-backup-restore.tls=true
        - traefik.http.routers.pg-backup-restore.tls.certresolver=le
        - traefik.http.services.pg-backup-restore.loadbalancer.server.port=3000
        - traefik.http.services.pg-backup-restore.loadbalancer.server.scheme=http
    networks:
      - premas-2026

networks:
  premas-2026:
    external: true
